In [1]:
import numpy as np

对于ndarray结构来说，里面所有的元素必须是同一类型的
如果不是的话，会自动的向下进行转换

In [2]:
tang_list = [1,2,3,4,5]
tang_array = np.array(tang_list)
tang_array

array([1, 2, 3, 4, 5])

ndarray基本属性操作

In [3]:
type(tang_array)

numpy.ndarray

In [4]:
tang_array.dtype

dtype('int64')

In [5]:
tang_array.itemsize

8

In [6]:
tang_array.shape

(5,)

In [7]:
tang_array.size

5

In [8]:
np.size(tang_array)

5

In [9]:
np.shape(tang_array)

(5,)

In [10]:
tang_array.ndim

1

In [11]:
tang_array

array([1, 2, 3, 4, 5])

In [12]:
tang_array.fill(0)
tang_array

array([0, 0, 0, 0, 0])

索引与切片:跟Python都是一样的 还是从0开始的

In [13]:
tang_list = [1,2,3,4,5]
tang_array = np.array(tang_list)
tang_array[0]

np.int64(1)

In [14]:
tang_array[1:3]

array([2, 3])

In [15]:
tang_array[-2:]

array([4, 5])

矩阵格式（多维的形式）

In [16]:
tang_array = np.array([[1,2,3],
                      [4,5,6],
                      [7,8,9]])
tang_array

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [17]:
tang_array.shape

(3, 3)

In [18]:
tang_array.size

9

In [19]:
tang_array.ndim

2

In [20]:
tang_array[1,1]

np.int64(5)

In [21]:
tang_array[1,1] = 10
tang_array

array([[ 1,  2,  3],
       [ 4, 10,  6],
       [ 7,  8,  9]])

In [22]:
tang_array[1]

array([ 4, 10,  6])

In [23]:
tang_array[:,1]

array([ 2, 10,  8])

In [24]:
tang_array[0,0:2]

array([1, 2])

In [25]:
tang_array

array([[ 1,  2,  3],
       [ 4, 10,  6],
       [ 7,  8,  9]])

In [26]:
tang_array2 = tang_array
tang_array2

array([[ 1,  2,  3],
       [ 4, 10,  6],
       [ 7,  8,  9]])

In [27]:
tang_array2[1,1] = 100
tang_array2

array([[  1,   2,   3],
       [  4, 100,   6],
       [  7,   8,   9]])

In [28]:
tang_array

array([[  1,   2,   3],
       [  4, 100,   6],
       [  7,   8,   9]])

In [30]:
tang_array2 = tang_array.copy()
tang_array2

array([[  1,   2,   3],
       [  4, 100,   6],
       [  7,   8,   9]])

In [31]:
tang_array2[1,1] = 10000
tang_array2

array([[    1,     2,     3],
       [    4, 10000,     6],
       [    7,     8,     9]])

In [32]:
tang_array

array([[  1,   2,   3],
       [  4, 100,   6],
       [  7,   8,   9]])

In [33]:
tang_array = np.arange(0,100,10)
tang_array

array([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [34]:
mask = np.array([0,0,0,1,1,1,0,0,1,1],dtype=bool)
mask

array([False, False, False,  True,  True,  True, False, False,  True,
        True])

In [35]:
tang_array[mask]

array([30, 40, 50, 80, 90])

In [36]:
random_array = np.random.rand(10)
random_array

array([0.12874612, 0.61045979, 0.43950408, 0.36488907, 0.23426907,
       0.95169739, 0.14779227, 0.58936341, 0.44226847, 0.85101776])

In [37]:
mask = random_array > 0.5
mask

array([False,  True, False, False, False,  True, False,  True, False,
        True])

In [38]:
tang_array[mask]

array([10, 50, 70, 90])

In [39]:
tang_array = np.array([10,20,30,40,50])
tang_array > 30

array([False, False, False,  True,  True])

In [40]:
np.where(tang_array > 30)

(array([3, 4]),)

In [41]:
tang_array[np.where(tang_array > 30)]

array([40, 50])

In [42]:
tang_array = np.array([1,2,3,4,5],dtype=np.float32)
tang_array

array([1., 2., 3., 4., 5.], dtype=float32)

In [43]:
tang_array.dtype

dtype('float32')

In [44]:
tang_array.nbytes

20

In [47]:
tang_array = np.array([1,10,3.5,'str'],dtype = object)
tang_array

array([1, 10, 3.5, 'str'], dtype=object)

In [48]:
tang_array * 2

array([2, 20, 7.0, 'strstr'], dtype=object)

In [49]:
tang_array = np.array([1,2,3,4,5])
np.asarray(tang_array,dtype = np.float32)

array([1., 2., 3., 4., 5.], dtype=float32)

In [50]:
tang_array

array([1, 2, 3, 4, 5])

In [51]:
tang_array2 = np.asarray(tang_array,dtype = np.float32)

In [52]:
tang_array2

array([1., 2., 3., 4., 5.], dtype=float32)

In [53]:
tang_array

array([1, 2, 3, 4, 5])

In [54]:
tang_array.astype(np.float32)

array([1., 2., 3., 4., 5.], dtype=float32)

In [55]:
tang_array 

array([1, 2, 3, 4, 5])