### 数组形状操作

In [1]:
import numpy as np
tang_array = np.arange(10)
tang_array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [2]:
tang_array.shape

(10,)

In [3]:
tang_array.shape = 2,5

In [4]:
tang_array

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [5]:
tang_array.reshape(1,10)

array([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]])

大小必须不能改变

In [6]:
tang_array .shape = 3,4

ValueError: cannot reshape array of size 10 into shape (3,4)

In [7]:
tang_array = np.arange(10)
tang_array.shape

(10,)

In [8]:
tang_array = tang_array[np.newaxis,:]
tang_array.shape

(1, 10)

In [9]:
tang_array = np.arange(10)
tang_array.shape

(10,)

In [10]:
tang_array = tang_array[:,np.newaxis]
tang_array.shape

(10, 1)

In [11]:
tang_array = tang_array[:,np.newaxis,np.newaxis]
tang_array.shape

(10, 1, 1, 1)

In [12]:
tang_array = tang_array.squeeze()
tang_array.shape

(10,)

In [13]:
tang_array.shape = 2,5

In [14]:
tang_array

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [15]:
tang_array.transpose()

array([[0, 5],
       [1, 6],
       [2, 7],
       [3, 8],
       [4, 9]])

In [16]:
tang_array.T

array([[0, 5],
       [1, 6],
       [2, 7],
       [3, 8],
       [4, 9]])

In [17]:
tang_array

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

### 数组的连接

In [18]:
a = np.array([[123,456,678],[3214,456,134]])
a

array([[ 123,  456,  678],
       [3214,  456,  134]])

In [19]:
b = np.array([[1235,3124,432],[43,13,134]])
b

array([[1235, 3124,  432],
       [  43,   13,  134]])

In [20]:
c = np.concatenate((a,b))
c

array([[ 123,  456,  678],
       [3214,  456,  134],
       [1235, 3124,  432],
       [  43,   13,  134]])

In [21]:
c = np.concatenate((a,b),axis = 0)
c

array([[ 123,  456,  678],
       [3214,  456,  134],
       [1235, 3124,  432],
       [  43,   13,  134]])

In [22]:
c = np.concatenate((a,b),axis = 1)
c

array([[ 123,  456,  678, 1235, 3124,  432],
       [3214,  456,  134,   43,   13,  134]])

In [23]:
c.shape

(2, 6)

In [24]:
np.vstack((a,b))

array([[ 123,  456,  678],
       [3214,  456,  134],
       [1235, 3124,  432],
       [  43,   13,  134]])

In [25]:
np.hstack((a,b))

array([[ 123,  456,  678, 1235, 3124,  432],
       [3214,  456,  134,   43,   13,  134]])

In [26]:
a

array([[ 123,  456,  678],
       [3214,  456,  134]])

In [27]:
a.flatten()

array([ 123,  456,  678, 3214,  456,  134])

In [28]:
a


array([[ 123,  456,  678],
       [3214,  456,  134]])

In [29]:
a.ravel()

array([ 123,  456,  678, 3214,  456,  134])