### Numpy的随机模块

In [1]:
import numpy as np
#所有的值都是从0到1
np.random.rand(3,2)

array([[0.19495145, 0.29832818],
       [0.71099539, 0.51366366],
       [0.59177838, 0.52778883]])

In [2]:
#返回的是随机的整数，左闭右开
np.random.randint(10,size = (5,4))

array([[3, 9, 2, 1],
       [7, 4, 6, 9],
       [1, 3, 3, 2],
       [1, 6, 6, 7],
       [1, 7, 1, 0]], dtype=int32)

In [3]:
np.random.rand()

0.49117941299018786

In [4]:
np.random.random_sample()

0.2107652599127111

In [5]:
np.random.randint(0,10,3)

array([9, 7, 0], dtype=int32)

In [6]:
mu, sigma = 0,0.1
np.random.normal(mu,sigma,10)

array([-0.09029333, -0.07547823,  0.1229216 ,  0.12437103,  0.02271914,
        0.18231001,  0.0388345 ,  0.10357319,  0.02617813, -0.0804662 ])

In [7]:
np.set_printoptions(precision = 2)

In [8]:
mu, sigma = 0,0.1
np.random.normal(mu,sigma,10)

array([-0.14, -0.06, -0.02,  0.2 ,  0.09, -0.17, -0.04,  0.  ,  0.06,
        0.06])

### 洗牌

In [9]:
tang_array = np.arange(10)
tang_array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [10]:
np.random.shuffle(tang_array)

In [11]:
tang_array

array([9, 1, 2, 4, 3, 6, 0, 5, 7, 8])

### 随机的种子

In [12]:
np.random.seed(100)

In [13]:
mu, sigma = 0,0.1
np.random.normal(mu,sigma,10)

array([-0.17,  0.03,  0.12, -0.03,  0.1 ,  0.05,  0.02, -0.11, -0.02,
        0.03])