## Numpy练习题

打印当前Numpy版本

In [1]:
import numpy as np

In [3]:
print (np.__version__)

1.13.0


构造一个全零的矩阵，并打印其占用的内存大小

In [2]:
z = np.zeros((5,5))
print ('%d bytes'%(z.size * z.itemsize))

200 bytes


打印一个函数的帮助文档，比如numpy.add

In [3]:
print (help(np.info(np.add)))

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.
    If ``x1.shape != x2.shape``, they must be broadcastable to a common
    shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be set to the ufunc result.
    Elsewhere, the `out` array will retain its original value.
    Note that if an uninitialized `out` array is created via the default
    ``out=None``,

创建一个10-49的数组，并将其倒序排列

In [4]:
tang_array = np.arange(10,50,1)
tang_array = tang_array[::-1]
tang_array

array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10])

找到一个数组中不为0的索引

In [5]:
np.nonzero([1,2,3,4,5,0,0,0,1234,0,1])

(array([ 0,  1,  2,  3,  4,  8, 10]),)

随机构造一个3*3矩阵，并打印其中最大与最小值

In [6]:
tang_array = np.random.random((3,3))
tang_array.min()
tang_array.max()

np.float64(0.8037296514142216)

构造一个5*5的矩阵，令其值都为1，并在最外层加上一圈0

In [7]:
tang_array = np.ones((5,5))
tang_array = np.pad(tang_array,pad_width = 2,mode = 'constant',constant_values = 0)
tang_array

array([[0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 1., 1., 1., 1., 0., 0.],
       [0., 0., 1., 1., 1., 1., 1., 0., 0.],
       [0., 0., 1., 1., 1., 1., 1., 0., 0.],
       [0., 0., 1., 1., 1., 1., 1., 0., 0.],
       [0., 0., 1., 1., 1., 1., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [9]:
print (help(np.pad))

Help on _ArrayFunctionDispatcher in module numpy:

pad(array, pad_width, mode='constant', **kwargs)
    Pad an array.

    Parameters
    ----------
    array : array_like of rank N
        The array to pad.
    pad_width : {sequence, array_like, int}
        Number of values padded to the edges of each axis.
        ``((before_1, after_1), ... (before_N, after_N))`` unique pad widths
        for each axis.
        ``(before, after)`` or ``((before, after),)`` yields same before
        and after pad for each axis.
        ``(pad,)`` or ``int`` is a shortcut for before = after = pad width
        for all axes.
    mode : str or function, optional
        One of the following string values or a user supplied function.

        'constant' (default)
            Pads with a constant value.
        'edge'
            Pads with the edge values of array.
        'linear_ramp'
            Pads with the linear ramp between end_value and the
            array edge value.
        'maximum'
      

构建一个shape为（6，7，8）的矩阵，并找到第100个元素的索引值

In [10]:
np.unravel_index(100,(6,7,8))

(np.int64(1), np.int64(5), np.int64(4))

对一个5*5的矩阵做归一化操作

In [11]:
tang_array = np.random.random((5,5))
tang_max = tang_array.max()
tang_min = tang_array.min()
tang_array = (tang_array-tang_min)/(tang_max - tang_min)
tang_array

array([[0.65993266, 0.65932139, 0.5542011 , 0.57629159, 0.75688502],
       [0.60809069, 0.1569876 , 0.30947409, 0.46403421, 1.        ],
       [0.40373546, 0.        , 0.35926768, 0.16125305, 0.86982068],
       [0.59277796, 0.31940171, 0.13022028, 0.44308156, 0.92307917],
       [0.35958066, 0.02608449, 0.17146301, 0.18926366, 0.99608999]])

找到两个数组中相同的值

In [12]:
z1 = np.random.randint(0,10,10) 
z2 = np.random.randint(0,10,10)
print (z1)
print (z2)
print (np.intersect1d(z1,z2))

[3 3 9 7 0 4 1 8 3 3]
[9 0 6 8 7 6 7 7 4 7]
[0 4 7 8 9]


得到今天 明天 昨天的日期

In [13]:
yesterday = np.datetime64('today','D') - np.timedelta64(1,'D')
today = np.datetime64('today','D')
tommorow = np.datetime64('today','D') + np.timedelta64(1,'D')

In [14]:
yesterday

np.datetime64('2025-11-14')

In [15]:
today

np.datetime64('2025-11-15')

In [16]:
tommorow

np.datetime64('2025-11-16')

得到一个月中所有的天

In [18]:
np.arange('2025-10','2025-11',dtype='datetime64[D]')

array(['2025-10-01', '2025-10-02', '2025-10-03', '2025-10-04',
       '2025-10-05', '2025-10-06', '2025-10-07', '2025-10-08',
       '2025-10-09', '2025-10-10', '2025-10-11', '2025-10-12',
       '2025-10-13', '2025-10-14', '2025-10-15', '2025-10-16',
       '2025-10-17', '2025-10-18', '2025-10-19', '2025-10-20',
       '2025-10-21', '2025-10-22', '2025-10-23', '2025-10-24',
       '2025-10-25', '2025-10-26', '2025-10-27', '2025-10-28',
       '2025-10-29', '2025-10-30', '2025-10-31'], dtype='datetime64[D]')

得到一个数的整数部分


In [19]:
z = np.random.uniform(0,10,10)
np.floor(z)

array([4., 8., 6., 3., 0., 5., 8., 9., 3., 1.])

构造一个数组，让它不能被改变

In [20]:
z = np.zeros(5)
z.flags.writeable = False
z[0] = 1

ValueError: assignment destination is read-only

打印大数据的部分值，全部值

In [21]:
np.set_printoptions(threshold=5)
z = np.zeros((15,15))
z

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]], shape=(15, 15))

找到在一个数组中，最接近一个数的索引

In [22]:
z = np.arange(100)
v = np.random.uniform(0,100)
print (v)
index = (np.abs(z-v)).argmin()
print (z[index])

60.40612467554985
60


32位float类型和32位int类型转换

In [23]:
z = np.arange(10,dtype=np.int32)
print (z.dtype)
z = z.astype(np.float32)
print (z.dtype)

int32
float32


打印数组元素位置坐标与数值

In [24]:
z = np.arange(9).reshape(3,3)
for index,value in np.ndenumerate(z):
    print (index,value)

(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8


按照数组的某一列进行排序

In [25]:
z = np.random.randint(0,10,(3,3))
print (z)
print (z[z[:,1].argsort()])

[[7 3 2]
 [3 6 7]
 [1 9 6]]
[[7 3 2]
 [3 6 7]
 [1 9 6]]


统计数组中每个数值出现的次数

In [26]:
z = np.array([1,1,1,2,2,3,3,4,5,8])
np.bincount(z)

array([0, 3, 2, ..., 0, 0, 1], shape=(9,))

如何对一个四维数组的最后两维来求和

In [27]:
z = np.random.randint(0,10,(4,4,4,4))
res = z.sum(axis=(-2,-1))
res

array([[68, 93, 71, 69],
       [83, 56, 63, 75],
       [88, 76, 67, 49],
       [75, 75, 72, 53]], shape=(4, 4))

交换矩阵中的两行

In [28]:
z = np.arange(25).reshape(5,5)
z[[0,1]] = z[[1,0]]
z


array([[ 5,  6,  7,  8,  9],
       [ 0,  1,  2,  3,  4],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]], shape=(5, 5))

找到一个数组中最常出现的数字

In [29]:
z = np.random.randint(0,10,50)
print (np.bincount(z).argmax())

2


快速查找TOP K

In [30]:
z = np.arange(10000)
np.random.shuffle(z)
n = 5
print (z[np.argpartition(-z,n)[:n]])

[9999 9998 9997 9996 9995]


去除掉一个数组中，所有元素都相同的数据

In [32]:
np.set_printoptions(threshold=None)
z = np.random.randint(0,3,(10,3))
z

array([[0, 0, 2],
       [0, 0, 2],
       [1, 1, 2],
       ...,
       [2, 1, 0],
       [0, 1, 1],
       [1, 1, 0]], shape=(10, 3), dtype=int32)

In [33]:
e = np.all(z[:,1:] == z[:,:-1],axis = 1)
print (e)

[False False False ... False False False]


In [34]:
a = np.array([1,2,3,4])
b = np.array([1,2,3,5])
np.all(a == b)

np.False_

In [35]:
np.any(a == b)

np.True_